---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: grafana-sa-token
  namespace: grafana
  annotations:
    - kubernetes.io/service-account.name: grafana-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: grafana
secrets:
- name: grafana-sa-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rancher-monitoring-grafana-clusterrole
subjects:
- kind: ServiceAccount
  name: grafana-sa
  namespace: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - env:
            - name: METHOD
            - name: LABEL
              value: grafana_dashboard
            - name: FOLDER
              value: /tmp/dashboards
            - name: RESOURCE
              value: both
            - name: NAMESPACE
              value: cattle-dashboards
          image: rancher/mirrored-kiwigrid-k8s-sidecar:1.12.3
          imagePullPolicy: IfNotPresent
          name: grafana-sc-dashboard
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /tmp/dashboards
              name: sc-dashboard-volume
          resources: {}
        - name: grafana
          image: grafana/grafana:8.5.15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv
            - mountPath: /tmp/dashboards
              name: sc-dashboard-volume
          env:
            - name: GF_PATHS_DATA
              value: /var/lib/grafana/
            - name: GF_PATHS_LOGS
              value: /var/log/grafana
            - name: GF_PATHS_PLUGINS
              value: /var/lib/grafana/plugins
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
      serviceAccount: grafana-sa
      serviceAccountName: grafana-sa
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - emptyDir: {}
          name: sc-dashboard-volume
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana
      nodePort: 30001
  selector:
    app: grafana
  sessionAffinity: None
#  type: LoadBalancer
  type: NodePort
